# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
name: API automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn install -f pxp-api/pom.xml
    - name: Save test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
          name: test-result
          path: |
            pxp-api/test-result
